version: '3.8'

services:
  app:
    build:
      context: .
    command:
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/files/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:$PGDATA
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    user: app_user
    command: [
      "celery",
      "-A",
      "library_service",
      "worker",
      "--loglevel=info"
    ]
    volumes:
      - .:/app
    depends_on:
      - redis

  celerybeat:
    build: .
    user: app_user
    command: [
      "celery",
      "-A",
      "library_service",
      "beat",
      "--loglevel=info",
      "--scheduler",
      "django_celery_beat.schedulers:DatabaseScheduler",
    ]
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  media_data:
