version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/files/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:$PGDATA
    env_file:
      - .env

volumes:
  postgres_data:
  media_data:
